#* Deployment setup, no hot-reload, no volume mapping, no database. Runs server with "go run main.go" and client with a build step. Passes database connection details via .env file.
#* Should run with: docker-compose -f docker-compose.yaml -f docker-compose.deploy.yaml --build

version: "3.8"
services:
  client:
    build:
      context: ./client
      args:
        - BUILD_ENV=production
    environment:
      FAVICON_PATH: "app/favicon.ico"
      API_BASE_URL: ${API_BASE_URL}
    command: ["node", ".output/server/index.mjs"]
  server:
    build:
      context: ./server
      args:
        - BUILD_ENV=production
    environment:
      IS_PRODUCTION: "true"
      PRODUCTION_DOMAIN: ${PRODUCTION_DOMAIN}
      SERVER_PORT: "3001"
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DBNAME: ${DB_DBNAME}
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}
    command: ["go", "run", "main.go"]
