version: "3.8"
services:
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    restart: on-failure

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: on-failure
