version: "3.8"

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: dockerfile
    depends_on:
      - database
    volumes:
      - ./server:/app
    ports:
      - "3001:3001"
    environment:
      SERVER_SERVER_HOST: 0.0.0.0
      SERVER_SERVER_PORT: 3001
      SERVER_DATABASE_HOST: database
      SERVER_DATABASE_PORT: 5432
      SERVER_DATABASE_DBNAME: postgres
      SERVER_DATABASE_USER: postgres
      SERVER_DATABASE_PASSWORD: password
      SERVER_DATABASE_SSLMODE: prefer

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: dockerfile
  #     args:
  #       - BUILD_ENV=development
  #   depends_on:
  #     - server
  #     - database
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     API_BASE_URL: http://localhost:3001
  #   command: ["bun", "run", "dev"]

volumes:
  postgres-data:
