version: "3.8"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: verve
    restart: on-failure

  server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    restart: on-failure

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
      - postgres
    restart: on-failure
