basePath: /api/v1
definitions:
  auth.Credentials:
    properties:
      confirmPassword:
        type: string
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  common.APIResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
host: localhost:3001
info:
  contact:
    email: phyokyawsoe89@gmail.com
    name: alsey89
  description: This server provides APIs for the Verve HRMS application
  license:
    name: GPL 3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  title: Verve HRMS API
  version: "1.0"
paths:
  /auth/check:
    get:
      consumes:
      - application/json
      description: Check if the user is authenticated and if they are an admin
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/common.APIResponse'
        "400":
          description: admin status not found
          schema:
            $ref: '#/definitions/common.APIResponse'
      summary: Check authentication status
      tags:
      - auth
  /auth/signin:
    post:
      consumes:
      - application/json
      description: Authenticate a user and start a session
      parameters:
      - description: Signin Credentials
        in: body
        name: creds
        required: true
        schema:
          $ref: '#/definitions/auth.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: user has been signed in
          schema:
            $ref: '#/definitions/common.APIResponse'
        "401":
          description: invalid Credentials
          schema:
            $ref: '#/definitions/common.APIResponse'
        "404":
          description: user Not Found
          schema:
            $ref: '#/definitions/common.APIResponse'
        "500":
          description: internal Server Error
          schema:
            $ref: '#/definitions/common.APIResponse'
      summary: User signin
      tags:
      - auth
  /auth/signout:
    post:
      consumes:
      - application/json
      description: End a user's session
      produces:
      - application/json
      responses:
        "200":
          description: user has been signed out
          schema:
            $ref: '#/definitions/common.APIResponse'
      summary: User signout
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: Signup Credentials
        in: body
        name: creds
        required: true
        schema:
          $ref: '#/definitions/auth.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: user has been signed up and signed in
          schema:
            $ref: '#/definitions/common.APIResponse'
        "400":
          description: invalid email
          schema:
            $ref: '#/definitions/common.APIResponse'
        "409":
          description: email not available
          schema:
            $ref: '#/definitions/common.APIResponse'
        "500":
          description: something went wrong
          schema:
            $ref: '#/definitions/common.APIResponse'
      summary: User signup
      tags:
      - auth
swagger: "2.0"
