# LOCAL DEV VARIABLES

#! Environment type
is_production: false

#! Local PostgreSQL
db:
  host: "postgres"
  user: "postgres"
  password: "postgres"
  dbname: "verve"
  port: "5432"
  sslmode: "disable"

#! JWT secret
jwt_secret: "thiskeyisfordevelopmentonly"

#! Server and client URLs
production_domain: null #set to actual domain in production
client_url: "http://localhost:3000"
client_port: 3000
server_url: "http://localhost:3001"
server_port: 3001
