# LOCAL DEV VARIABLES

#! Environment type
is_production: false

#! Local PostgreSQL
db:
  host: "postgres"
  user: "postgres"
  password: "postgres"
  dbname: "hrms"
  port: "5432"
  sslmode: "disable"

#! JWT secret
jwt_secret: "thiskeyisfordevelopmentonly"

#! DOMAINS AND URLS
production_domain: null #set to actual domain in production
