# LOCAL DEV VARIABLES

#! Environment type
is_production: false
production_domain: null #set to actual domain in production

#! Server and client URLs
client_url: "http://localhost:3000"
client_port: 3000
server_url: "http://localhost:3001"
server_port: 3001

#! Local PostgreSQL
db:
  host: "postgres"
  user: "postgres"
  password: "postgres"
  dbname: "hrms"
  port: "5432"
  sslmode: "disable"

#! JWT secret
jwt_secret: "thiskeyisfordevelopmentonly"
